### ISSUE TITLE
OpenMaya as the name for the project is conflicting with Autodesk's library

### ISSUE THREAD

**Issue by steel3d** [haggi/OpenMaya#191]
It's pretty confusing to be naming this project the same as Autodesk's internal library:

http://download.autodesk.com/us/maya/2011help/API/group___open_maya.html

**Comment by haggi** [comment]
Yes, it may confuse a few people, but I decided to ignore it because the project opens maya to other renderers, so why not naming it this way? Unless Autodesk complains about it of course...
